In [7]:
train_file_path = r"C:\Users\aniyant\Visual-Code-Projects\ml-project\machine-learning-project\housing\artifact\data_ingestion\2022-07-05-13-48-13\ingested_data\train\housing.csv"

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(train_file_path)


In [10]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.89     37.29                38.0       1568.0           351.0   
1    -121.93     37.05                14.0        679.0           108.0   
2    -117.20     32.77                31.0       1952.0           471.0   
3    -119.61     36.31                25.0       1847.0           371.0   
4    -118.59     34.23                17.0       6592.0          1525.0   

   population  households  median_income  median_house_value ocean_proximity  
0       710.0       339.0         2.7042            286600.0       <1H OCEAN  
1       306.0       113.0         6.4214            340600.0       <1H OCEAN  
2       936.0       462.0         2.8621            196900.0      NEAR OCEAN  
3      1460.0       353.0         1.8839             46300.0          INLAND  
4      4459.0      1463.0         3.0347            254500.0       <1H OCEAN

In [5]:
df.shape

(16512, 10)

In [11]:
x,y = df.drop(columns=["median_house_value"],axis = 1), df[["median_house_value"]]

In [12]:
x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.89     37.29                38.0       1568.0           351.0   
1    -121.93     37.05                14.0        679.0           108.0   
2    -117.20     32.77                31.0       1952.0           471.0   
3    -119.61     36.31                25.0       1847.0           371.0   
4    -118.59     34.23                17.0       6592.0          1525.0   

   population  households  median_income ocean_proximity  
0       710.0       339.0         2.7042       <1H OCEAN  
1       306.0       113.0         6.4214       <1H OCEAN  
2       936.0       462.0         2.8621      NEAR OCEAN  
3      1460.0       353.0         1.8839          INLAND  
4      4459.0      1463.0         3.0347       <1H OCEAN

In [13]:
x.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
numerical_column = x.drop(columns=['ocean_proximity'],axis=1)

In [14]:
numerical_column.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [15]:
cat_column = x['ocean_proximity']

In [16]:
simple_imputer = SimpleImputer(strategy="median")

In [13]:
simple_imputer.fit(numerical_column)

SimpleImputer(strategy='median')

In [14]:
simple_imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2119.5   ,  433.    , 1164.    ,
        408.    ,    3.5409])

In [17]:
transform_df = simple_imputer.transform(X=numerical_column)
transform_df

NotFittedError: This SimpleImputer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [18]:
df= pd.DataFrame(transform_df)

In [19]:
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [20]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [21]:
simple_imputer.fit_transform(numerical_column)

array([[-121.89  ,   37.29  ,   38.    , ...,  710.    ,  339.    ,
           2.7042],
       [-121.93  ,   37.05  ,   14.    , ...,  306.    ,  113.    ,
           6.4214],
       [-117.2   ,   32.77  ,   31.    , ...,  936.    ,  462.    ,
           2.8621],
       ...,
       [-116.4   ,   34.09  ,    9.    , ..., 2098.    ,  765.    ,
           3.2723],
       [-118.01  ,   33.82  ,   31.    , ..., 1356.    ,  356.    ,
           4.0625],
       [-122.45  ,   37.77  ,   52.    , ..., 1269.    ,  639.    ,
           3.575 ]])

In [22]:
x.ocean_proximity.isnull().sum()

0

In [23]:
x.ocean_proximity.value_counts()

<1H OCEAN     7276
INLAND        5263
NEAR OCEAN    2124
NEAR BAY      1847
ISLAND           2
Name: ocean_proximity, dtype: int64

In [18]:
simple_imputer = SimpleImputer(strategy="most_frequent")

In [19]:
from sklearn.base import BaseEstimator, TransformerMixin

In [26]:
class Test:
    def __init__(self,strategy="median"):
        self.strategy = strategy

    def fit(self,X):
        self.features_ = X.columns
        self.statistics_ = []

        for column in X.columns:
            self.statistics_.append(X[column].median())
        
        return self

    def transform(self,X:pd.DataFrame):
        for idx,column in enumerate(X.columns):
            #print(idx,column)
            #print(self.statistics_[idx])
            X[column].fillna(self.statistics_[idx],inplace=True)
        return X

    def fit_transform(self,X:pd.DataFrame):
        self.fit(X=X)
        return self.transform(X)

In [27]:
t = Test(strategy="median")
t.fit(X=numerical_column)


In [28]:
df = t.transform(numerical_column)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.89     37.29                38.0       1568.0           351.0   
1    -121.93     37.05                14.0        679.0           108.0   
2    -117.20     32.77                31.0       1952.0           471.0   
3    -119.61     36.31                25.0       1847.0           371.0   
4    -118.59     34.23                17.0       6592.0          1525.0   

   population  households  median_income  
0       710.0       339.0         2.7042  
1       306.0       113.0         6.4214  
2       936.0       462.0         2.8621  
3      1460.0       353.0         1.8839  
4      4459.0      1463.0         3.0347

In [29]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

In [20]:
class Test(BaseEstimator,TransformerMixin):
    def __init__(self,strategy="median"):
        self.strategy = strategy

    def fit(self,X):
        self.features_ = X.columns
        self.statistics_ = []

        for column in X.columns:
            self.statistics_.append(X[column].median())
        
        return self

    def transform(self,X:pd.DataFrame):
        for idx,column in enumerate(X.columns):
            #print(idx,column)
            #print(self.statistics_[idx])
            X[column].fillna(self.statistics_[idx],inplace=True)
        return X



In [35]:
t = Test()

In [37]:
df = t.fit_transform(numerical_column)

In [38]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

In [39]:
t.statistics_

[-118.51, 34.26, 29.0, 2119.5, 433.0, 1164.0, 408.0, 3.5408999999999997]

In [40]:
import numpy as np

In [42]:
x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.89     37.29                38.0       1568.0           351.0   
1    -121.93     37.05                14.0        679.0           108.0   
2    -117.20     32.77                31.0       1952.0           471.0   
3    -119.61     36.31                25.0       1847.0           371.0   
4    -118.59     34.23                17.0       6592.0          1525.0   

   population  households  median_income ocean_proximity  
0       710.0       339.0         2.7042       <1H OCEAN  
1       306.0       113.0         6.4214       <1H OCEAN  
2       936.0       462.0         2.8621      NEAR OCEAN  
3      1460.0       353.0         1.8839          INLAND  
4      4459.0      1463.0         3.0347       <1H OCEAN

In [43]:
x.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [21]:
COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"
COLUMN_TOTAL_BEDROOM = "total_bedrooms"

class FeatureGenerator(BaseEstimator, TransformerMixin):

    def __init__(self, add_bedrooms_per_room=True,
                 total_rooms_ix=3,
                 population_ix=5,
                 households_ix=6,
                 total_bedrooms_ix=4, columns=None):
        """
        FeatureGenerator Initialization
        add_bedrooms_per_room: bool
        total_rooms_ix: int index number of total rooms columns
        population_ix: int index number of total population columns
        households_ix: int index number of  households columns
        total_bedrooms_ix: int index number of bedrooms columns
        """
        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix = self.columns.index(COLUMN_POPULATION)
                households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix = self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_rooms_ix = total_rooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            self.total_bedrooms_ix = total_bedrooms_ix
        except Exception as e:
            raise e

    def fit(self, X, y=None):
        return self

    def transform(self, X, y=None):
        try:
            room_per_household = X[:, self.total_rooms_ix] / \
                                 X[:, self.households_ix]
            population_per_household = X[:, self.population_ix] / \
                                       X[:, self.households_ix]
            if self.add_bedrooms_per_room:
                bedrooms_per_room = X[:, self.total_bedrooms_ix] / \
                                    X[:, self.total_rooms_ix]
                generated_feature = np.c_[
                    X, room_per_household, population_per_household, bedrooms_per_room]
            else:
                generated_feature = np.c_[
                    X, room_per_household, population_per_household]

            return generated_feature
        except Exception as e:
            raise e


In [22]:
features = FeatureGenerator()

In [23]:
features.transform(X=x)

TypeError: '(slice(None, None, None), 3)' is an invalid key

In [73]:
room_per_household = x["total_rooms"]/x["households"]

In [104]:
arr1 = np.arange(10)
arr2 = np.arange(10)

In [105]:
np.c_[arr1,arr2]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import numpy as np

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
num_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="median")),
    ('feature_generator',FeatureGenerator()),
    ('scaling',StandardScaler())
])

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
cat_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('oneHotEncoder',OneHotEncoder()),
    ('scaling',StandardScaler(with_mean=False))
])

In [66]:
num_pipeline.fit_transform(X=numerical_column)

array([[-1.15604281,  0.77194962,  0.74333089, ..., -0.31205452,
        -0.08649871,  0.15531753],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.21768338,
        -0.03353391, -0.83628902],
       [ 1.18684903, -1.34218285,  0.18664186, ..., -0.46531516,
        -0.09240499,  0.4222004 ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.3469342 ,
        -0.03055414, -0.52177644],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.02499488,
         0.06150916, -0.30340741],
       [-1.43579109,  0.99645926,  1.85670895, ..., -0.22852947,
        -0.09586294,  0.10180567]])

In [29]:
cat_pipeline.fit_transform(X=pd.DataFrame(x['ocean_proximity']))

<16512x5 sparse matrix of type '<class 'numpy.float64'>'
	with 16512 stored elements in Compressed Sparse Row format>

In [30]:
numerical_column_name = numerical_column.columns

In [31]:
numerical_column_name

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [34]:
cat_column_name = ['ocean_proximity']

In [35]:
preprocessing = ColumnTransformer(transformers=[
    ('num_pipeline',num_pipeline,numerical_column_name),
    ('cat_pipeline',cat_pipeline,cat_column_name)
])

In [36]:
processed_df = preprocessing.fit_transform(df)

In [37]:
processed_df = pd.DataFrame(processed_df)

In [38]:
processed_df

0         1         2         3         4         5         6   \
0     -1.156043  0.771950  0.743331 -0.493234 -0.445438 -0.636211 -0.420698   
1     -1.176025  0.659695 -1.165317 -0.908967 -1.036928 -0.998331 -1.022227   
2      1.186849 -1.342183  0.186642 -0.313660 -0.153345 -0.433639 -0.093318   
3     -0.017068  0.313576 -0.290520 -0.362762 -0.396756  0.036041 -0.383436   
4      0.492474 -0.659299 -0.926736  1.856193  2.412211  2.724154  2.570975   
...         ...       ...       ...       ...       ...       ...       ...   
16507  0.722267 -0.673331  1.379547 -0.632123 -0.725361 -0.759010 -0.764049   
16508  1.007011 -0.823004  0.902385 -0.667196 -0.584183 -0.329664 -0.636291   
16509  1.586489 -0.724781 -1.562952  1.043901  0.822735  0.607904  0.713156   
16510  0.782213 -0.851068  0.186642 -0.309919 -0.374849 -0.057178 -0.375451   
16511 -1.435791  0.996459  1.856709  0.220853  0.360253 -0.135159  0.377791   

             7         8         9         10        11        12   13  \
0     -0.614937 -0.312055 -0.086499  0.155318  2.014241  0.000000  0.0   
1      1.336459  0.217683 -0.033534 -0.836289  2.014241  0.000000  0.0   
2     -0.532046 -0.465315 -0.092405  0.422200  0.000000  0.000000  0.0   
3     -1.045566 -0.079661  0.089736 -0.196453  0.000000  2.145982  0.0   
4     -0.441437 -0.357834 -0.004194  0.269928  2.014241  0.000000  0.0   
...         ...       ...       ...       ...       ...       ...  ...   
16507  0.554158  0.234352 -0.031755 -0.428853  0.000000  2.145982  0.0   
16508 -0.948815 -0.308114  0.084689  0.491503  0.000000  2.145982  0.0   
16509 -0.316705  0.346934 -0.030554 -0.521776  0.000000  2.145982  0.0   
16510  0.098121  0.024995  0.061509 -0.303407  2.014241  0.000000  0.0   
16511 -0.157799 -0.228529 -0.095863  0.101806  0.000000  0.000000  0.0   

             14       15  
0      0.000000  0.00000  
1      0.000000  0.00000  
2      0.000000  2.98691  
3      0.000000  0.00000  
4      0.000000  0.00000  
...         ...      ...  
16507  0.000000  0.00000  
16508  0.000000  0.00000  
16509  0.000000  0.00000  
16510  0.000000  0.00000  
16511  3.172672  0.00000  

[16512 rows x 16 columns]

In [39]:
import dill

In [40]:
with open('preprocessing.pkl','wb') as prep_file:
    dill.dump(preprocessing,prep_file)

In [43]:
with open("preprocessing.pkl",'rb') as prep:
    obj = dill.load(prep)

In [44]:
obj.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'], dtype=object)

In [45]:
obj.named_transformers_

{'num_pipeline': Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                 ('feature_generator', FeatureGenerator()),
                 ('scaling', StandardScaler())]),
 'cat_pipeline': Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                 ('oneHotEncoder', OneHotEncoder()),
                 ('scaling', StandardScaler(with_mean=False))]),
 'remainder': 'drop'}

In [46]:
obj.transformers_

[('num_pipeline',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                  ('feature_generator', FeatureGenerator()),
                  ('scaling', StandardScaler())]),
  Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
         'total_bedrooms', 'population', 'households', 'median_income'],
        dtype='object')),
 ('cat_pipeline',
  Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                  ('oneHotEncoder', OneHotEncoder()),
                  ('scaling', StandardScaler(with_mean=False))]),
  ['ocean_proximity']),
 ('remainder', 'drop', [8])]

In [47]:
obj.fit_transform(df)

array([[-1.15604281,  0.77194962,  0.74333089, ...,  0.        ,
         0.        ,  0.        ],
       [-1.17602483,  0.6596948 , -1.1653172 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.18684903, -1.34218285,  0.18664186, ...,  0.        ,
         0.        ,  2.9869105 ],
       ...,
       [ 1.58648943, -0.72478134, -1.56295222, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.78221312, -0.85106801,  0.18664186, ...,  0.        ,
         0.        ,  0.        ],
       [-1.43579109,  0.99645926,  1.85670895, ...,  0.        ,
         3.17267217,  0.        ]])